package oracle.ted.ipspregled.test.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import oracle.ted.ipspregled.test.common.AppModuleAM;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 29 14:16:33 CET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMClient extends ApplicationModuleImpl implements AppModuleAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMClient() {
    }

    public void executeSearchVo(String p_folder_id) {
        Object _ret = this.riInvokeExportedMethod(this,"executeSearchVo",new String [] {"java.lang.String"},new Object[] {p_folder_id});
        return;
    }
}
