package oracle.ted.ipspregled.test.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 29 14:16:33 CET 2018
// ---------------------------------------------------------------------
public interface AppModuleAM extends ApplicationModule {
    void executeSearchVo(String p_folder_id);
}
