package oracle.ted.ipspregled.uiview;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 23 10:40:27 CET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IpsMntFolderVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IpsMntFolderVOImpl() {
    }


}
