package oracle.ted.ipspregled.test;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;

import oracle.jbo.server.ViewObjectImpl;

import oracle.ted.ipspregled.test.common.AppModuleAM;
import oracle.ted.ipspregled.uiview.IpsMntFolderVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 29 12:17:19 CET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleAMImpl extends ApplicationModuleImpl implements AppModuleAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleAMImpl() {
    }

    /**
     * Container's getter for IpsMntFolder1.
     * @return IpsMntFolder1
     */
    public IpsMntFolderVOImpl getIpsMntFolder1() {
        return (IpsMntFolderVOImpl)findViewObject("IpsMntFolder1");
    }

    /**
     * Container's getter for IpsData1.
     * @return IpsData1
     */
    public ViewObjectImpl getIpsData1() {
        return (ViewObjectImpl)findViewObject("IpsData1");
    }

    /**
     * Container's getter for IpsMntFolder2.
     * @return IpsMntFolder2
     */
    public IpsMntFolderVOImpl getIpsMntFolder2() {
        return (IpsMntFolderVOImpl)findViewObject("IpsMntFolder2");
        
           }



    /**
     * Container's getter for IpsData2.
     * @return IpsData2
     */
    public ViewObjectImpl getIpsData2() {
        return (ViewObjectImpl)findViewObject("IpsData2");
    }
    
    public void executeSearchVo (String p_folder_id){
        System.out.println ("Folder_id je: " + p_folder_id );
        ViewObjectImpl traineeVo = this.getIpsData1();
        traineeVo.setApplyViewCriteriaName ("IpsDataVOCriteria"); //IpsMntFolderVOCriteria
        traineeVo.setNamedWhereClauseParam("p_folder_id", p_folder_id);
    
    
        traineeVo.executeQuery();
    }
    /**
     * Container's getter for IpsMntFolderFkLink1.
     * @return IpsMntFolderFkLink1
     */
    public ViewLinkImpl getIpsMntFolderFkLink1() {
        return (ViewLinkImpl)findViewLink("IpsMntFolderFkLink1");
    }

    /**
     * Container's getter for IpsDataFolderViewLink1.
     * @return IpsDataFolderViewLink1
     */
    public ViewLinkImpl getIpsDataFolderViewLink1() {
        return (ViewLinkImpl)findViewLink("IpsDataFolderViewLink1");
    }


}
